### ISSUE TITLE
Create a 404 Page 

### ISSUE THREAD

**Issue by RajatBhaskare7** [gdscrgpv/gdsc-website#1]
Create an amazing 404 page UI with proper working functionality so that when a user visits a page that does not exist, they are directed to the **404 page**.

**Comment by ujwalkumar1995** [comment]
Hey Rajat. I would like to work on this.

**Comment by ankurg132** [comment]
@ujwalkumar1995 go for it! 🚀

**Comment by ujwalkumar1995** [comment]
@ankurg132 @RajatBhaskare7 Have added a basic 404 page with redirect to home option. Would be open to suggestions with respect to styling or content.
Please have a look at the below PR.
#4

**Comment by ankurg132** [comment]
Congrats on making your PR @ujwalkumar1995! Onwards 🚀
