### ISSUE TITLE
Improve Readme.md File

### ISSUE THREAD

**Issue by ankurg132** [gdscrgpv/gdsc-website#16]
The current readme file is very abstract and following changes are suggested:

- The GDSC Logo is not in proper dimensions, a logo with full width and moderate height (the size of a banner in social media) should be added.
- There's a link containing Live Demo which redirects to nothing. We can remove this for now.
- In the installation section, only codes are mentioned without any guidelines as to how to use them. This should also be added to all the steps mentioned.
- Contributing and code of conduct links should be redirected to https://github.com/gdscrgpv/gdsc-website/blob/main/contributing.md and https://github.com/semikolan-co/code_of_conduct

**Comment by Giriraj-Roy** [comment]
Hello Sir,

I have gone through the repository and the given instructions. The issue seems to attract my interest and excites me to work on it. I humbly wait for you to assign the task to me if your analysis of my profile allows.

Yours Sincerely,
Giriraj Roy.

**Comment by ankurg132** [comment]
You can go for it, @Giriraj-Roy!
