### ISSUE TITLE
Improve the alignment of paragraph in mobile view 

### ISSUE THREAD

**Issue by codingkush** [gdscrgpv/gdsc-website#18]
Improve the alignment of paragraph in mobile view so that it's look good 

Screenshot:-------------> 
Mobile view

![Screenshot_20221013-201605](https://user-images.githubusercontent.com/78756312/195629974-b587a781-7c51-46b1-9fe6-c837065f58b6.png)

![Screenshot_20221013-201242](https://user-images.githubusercontent.com/78756312/195630046-378f93de-2edc-483f-b4cd-7c32d06d1df5.png)

**Comment by singh-manish1** [comment]
Please assign this to me.

**Comment by codingkush** [comment]
But i wanted to work in this 😔
